FROM python:3.12

WORKDIR /app

# Copy and install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY . .

# Default command to run the email analysis script
CMD ["python3", "main.py"]
